### PR TITLE
TG Update 7bf2f55

### PR DESCRIPTION
**Pull request by lessthnthree**

### CODE REVIEW

**Comment by distributivgesetz** [comment]
Please don't merge without uploading replacement screenshot tests again 😅

**Comment by lessthnthree** [comment]
yeah lol

**Comment by lessthnthree** [comment]
> Please don't merge without uploading replacement screenshot tests again 😅

screenshots are there, but changeling midround broke. https://github.com/effigy-se/effigy-se/issues/471 may be catching up

**Comment by unit0016** [comment]
Definitely is. We had a suggestion on how to handle that a bit ago, right? Or 'm I misremembering

**Pull request merged**
