### PR TITLE
Adjusted railings

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Adjusts the new railings so they line up properly. TM until it's sure all the end and end/flip variants look okay because it's not entirely clear where some of them are/supposed to be used.

## Changelog

:cl: LT3
image: Realigned railings
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
I really should just grab the old .dmi and compare/contrast on /tg/code for a fix there but 💀

**Comment by lessthnthree** [comment]
yeah there's nothing diff other than me changing the corners so they connect properly

maybe they styled it the way they did intentionally for some usage unseen?

**Comment by unit0016** [comment]
Nahh arc confirmed it was an accident

**Comment by lessthnthree** [comment]
Oh then

**Pull request merged**
