### PR TITLE
SkyyUI 1: Base/Character

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Block by block we will revamp the preferences menus, finally.

## Changelog

:cl: LT3
refactor: Preferences menus have been redesigned for some much needed QOL
qol: Chat radio colours have been adjusted to meet minimum contrast standards
/:cl:

### CODE REVIEW

**Comment by distributivgesetz** [comment]
why the file extensions in the imports?

**Comment by lessthnthree** [comment]
> why the file extensions in the imports?

https://github.com/tgstation/tgstation/pull/79898

**Comment by distributivgesetz** [comment]
ah, early port

**Comment by lessthnthree** [comment]
yes, tgui-dev-server dying while I'm trying to edit tgui everywhere was a bit of an issue

**Pull request merged**
