### PR TITLE
Wallening [IDB IGNORE] [MDB IGNORE]

### PR DESCRIPTION
**Pull request by lessthnthree**
Original PR: https://github.com/tgstation/tgstation/pull/85491

What's going on here
Kept you waitin huh!

This pr resprites most all walls, windows and other "wall adjacent" things to a 3/4th perspective, technical term is "tall" walls (we are very smart).

If you're trying to understand the technical details here, much of the "rendering tech" is built off the idea of split-vis. Basically, split a sprite up and render it on adjacent turfs, to prevent seeing "through" walls/doors, and to support seeing "edges" without actually seeing the atom itself.

Most of the rest of it is pipelining done to accommodate how icons are cut.

Path To Merge
Almost* all sprites and code is done at this point.
There are some things missing both on and off the bounty list, but that will be the case forever unless we force upstream (you guys) to stop adding new shit that doesn't fit the style.
I plan on accepting and integrating prs to the current working repo https://github.com/wall-nerds/wallening up until a merge, to make contribution simpler and allow things like bounties to close out more easily

This pr is quite bulky, even stripping away map changes it's maybe 7000 LOC (We have a few maps that were modified with UpdatePaths, I am also tentatively pring our test map, for future use.)
This may inhibit proper review, although that is part of why I am willing to make it despite my perfectionism. Apologies in advance.

Due to the perspective shift, a lot of mapping work is going to need to be done at some point. This comes in varying levels of priority. Many wallmounts are offset by hand, some are stuck in the wall/basically cannot be placed on the east/west/north edges of walls (posters), some just don't look great good in their current position.

Tests are currently a minor bit yorked, I thought it was more important to get this up then to clean them fully.

---

### Mapping

- [x] The Interlink
- [x] Rimpoint
- [x] Jungle Ruins
- [ ] Sigma Octantis
- [x] Ocean Ruins
- [x] Space Ruins
- [x] FoxHoleStation

### Code

- [x] Fix the wallening offset not being applied to mobs after they move

### Sprites
Flagged with EFFIGY TODO in-code

- [ ] ALL LIQUIDS
- [x] Rain
- [x] Firedoors
- [x] Fire Alarms
- [x] Wall Lights
- [x] Titanium Windows
- [x] Service Airlocks
- [x] Studio Airlocks

## Changelog

🆑 Raccoff, aa07, ActionNinja, ArcaneMusic, Armhulen, Azlan, Ben10Omintrix, BigBimmer, Capsandi, CapybaraExtravagante, Draco, Floyd, Iamgoofball, Imaginos16, Infrared, Jacquerel, Justice12354, Kryson, KylerAce, LemonInTheDark, LT3, Meyhazah, Mothblocks, MTandi, Ninjanomnom, oranges, Rohesie, Runi-c, san7890, Senefi, SimplyLogan, SomeAngryMiner, SpaceSmithers, Tattle, Thunder12345, Time-Green, Twaticus, unit0016, Viro, Waltermeldon, WatlerJe, ZephyrTFA with thanks to the Mojave Sun team!
add: Resprites or offsets almost all "tall" objects in the game to match a 3/4ths perspective
add: Bunch of rendering mumbo jumbo to make said 3/4ths perspective work
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
We have some pretty notable conflicts as a heads up (lot of wallmount sprites; alert states for fire alarms, firedoors; service/studio airlocks; shutters; etc etc etc.)

Most notable is that for some reason the moment a player moves they no longer respect the wallening offset; which is going to be a *big boy* problem.

**Comment by lessthnthree** [comment]
> We have some pretty notable conflicts as a heads up (lot of wallmount sprites; alert states for fire alarms, firedoors; service/studio airlocks; shutters; etc etc etc.)
> 
> Most notable is that for some reason the moment a player moves they no longer respect the wallening offset; which is going to be a _big boy_ problem.

lol what. I'll start testing and such tomorrow, now that the trammening is done

**Comment by unit0016** [comment]
I fixed a lot. Unchecked boxes are still fucked (or fucked but workable)

**Comment by lessthnthree** [comment]
yep. I'll do the fire/airlocks/lights, that's my code.

**Comment by unit0016** [comment]
Ah fuck I'll fix the Viro airlock

**Pull request merged**
