### PR TITLE
TG Update 40a8e0c

### PR DESCRIPTION
**Pull request by lessthnthree**

### CODE REVIEW

**Comment by unit0016** [comment]
@lessthnthree give this a fat sec for the respawn fix to be merged

**Comment by lessthnthree** [comment]
> @lessthnthree give this a fat sec for the respawn fix to be merged

oh?

**Comment by unit0016** [comment]
yeah, /tg/ screwed up slightly and are hotfixing a check that allowed people *not* allowed to respawn to.. do that.
lmao

**Comment by lessthnthree** [comment]
> yeah, /tg/ screwed up slightly and are hotfixing a check that allowed people _not_ allowed to respawn to.. do that. lmao

image

**Comment by unit0016** [comment]
good to move that in now

**Comment by lessthnthree** [comment]
> good to move that in now

Am I blind, what PR fixed it?

**Comment by unit0016** [comment]
> Am I blind, what PR fixed it?

78670

**Pull request closed without merging**
