### PR TITLE
Fix Effigy Whitelist

### PR DESCRIPTION
**Pull request by lessthnthree**

### CODE REVIEW

**Comment by distributivgesetz** [comment]
L45 needs to be changed to be `||` instead of `&&`

**Comment by lessthnthree** [comment]
> L45 needs to be changed to be `||` instead of `&&`

I split it in two

**Comment by distributivgesetz** [comment]
Ah I see the change now

**Comment by lessthnthree** [comment]
it works

**Comment by distributivgesetz** [comment]
Checking

**Pull request merged**
